name: Android CI

on:
  pull_request:
    branches: [ "develop" ]

jobs:
  build-views:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Config Env.properties
        run: echo '${{secrets.PUBLISH_DATA}}' > env.properties
      - name: Build with Gradle
        run: ./gradlew :imperiya:assembleViewsDebug

  build-compose:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Config Env.properties
        run: echo '${{secrets.PUBLISH_DATA}}' > env.properties
      - name: Build with Gradle
        run: ./gradlew :imperiya:assembleViewsDebug
