name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Config Env.properties
        run: echo '${{secrets.PUBLISH_DATA}}' > env.properties
      - name: Publish
        run: ./gradlew assemble publish 
          -Psigning.keyId=${{ secrets.KEY_ID }}
          -Psigning.password=${{ secrets.PASSWORD }}
          -Psigning.secretKeyRingFile=/home/runner/work/imperiya/imperiya/imperiya.gpg
